name: churn-train
on:
  push:
    paths:
      - churn/**
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./churn
        run: |
          cml ci --unshallow
          pip install -r requirements.txt
          dvc pull -v -r s3_storage       
          dvc repro
      - name: Create CML report
        working-directory: ./churn
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml pr --squash --skip-ci .
          echo "## Metrics" >> report.md
          dvc metrics diff main --show-md >> report.md

          # Publish confusion matrix diff
          echo "## Plots" >> report.md
          cml publish --md eval_plots/cm.png >> report.md 
          
          cml send-comment report.md
